// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	devopsv1 "github.com/stackvista/sandbox-operator/apis/devops/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSandboxes implements SandboxInterface
type FakeSandboxes struct {
	Fake *FakeDevopsV1
}

var sandboxesResource = schema.GroupVersionResource{Group: "devops.stackstate.com", Version: "v1", Resource: "sandboxes"}

var sandboxesKind = schema.GroupVersionKind{Group: "devops.stackstate.com", Version: "v1", Kind: "Sandbox"}

// Get takes name of the sandbox, and returns the corresponding sandbox object, and an error if there is any.
func (c *FakeSandboxes) Get(ctx context.Context, name string, options v1.GetOptions) (result *devopsv1.Sandbox, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(sandboxesResource, name), &devopsv1.Sandbox{})
	if obj == nil {
		return nil, err
	}
	return obj.(*devopsv1.Sandbox), err
}

// List takes label and field selectors, and returns the list of Sandboxes that match those selectors.
func (c *FakeSandboxes) List(ctx context.Context, opts v1.ListOptions) (result *devopsv1.SandboxList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(sandboxesResource, sandboxesKind, opts), &devopsv1.SandboxList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &devopsv1.SandboxList{ListMeta: obj.(*devopsv1.SandboxList).ListMeta}
	for _, item := range obj.(*devopsv1.SandboxList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sandboxes.
func (c *FakeSandboxes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(sandboxesResource, opts))
}

// Create takes the representation of a sandbox and creates it.  Returns the server's representation of the sandbox, and an error, if there is any.
func (c *FakeSandboxes) Create(ctx context.Context, sandbox *devopsv1.Sandbox, opts v1.CreateOptions) (result *devopsv1.Sandbox, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(sandboxesResource, sandbox), &devopsv1.Sandbox{})
	if obj == nil {
		return nil, err
	}
	return obj.(*devopsv1.Sandbox), err
}

// Update takes the representation of a sandbox and updates it. Returns the server's representation of the sandbox, and an error, if there is any.
func (c *FakeSandboxes) Update(ctx context.Context, sandbox *devopsv1.Sandbox, opts v1.UpdateOptions) (result *devopsv1.Sandbox, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(sandboxesResource, sandbox), &devopsv1.Sandbox{})
	if obj == nil {
		return nil, err
	}
	return obj.(*devopsv1.Sandbox), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSandboxes) UpdateStatus(ctx context.Context, sandbox *devopsv1.Sandbox, opts v1.UpdateOptions) (*devopsv1.Sandbox, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(sandboxesResource, "status", sandbox), &devopsv1.Sandbox{})
	if obj == nil {
		return nil, err
	}
	return obj.(*devopsv1.Sandbox), err
}

// Delete takes name of the sandbox and deletes it. Returns an error if one occurs.
func (c *FakeSandboxes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(sandboxesResource, name), &devopsv1.Sandbox{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSandboxes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(sandboxesResource, listOpts)

	_, err := c.Fake.Invokes(action, &devopsv1.SandboxList{})
	return err
}

// Patch applies the patch and returns the patched sandbox.
func (c *FakeSandboxes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *devopsv1.Sandbox, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(sandboxesResource, name, pt, data, subresources...), &devopsv1.Sandbox{})
	if obj == nil {
		return nil, err
	}
	return obj.(*devopsv1.Sandbox), err
}
