apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "fullname.short" . }}-cron
spec:
  schedule: {{ .Values.reaper.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ include "fullname.short" . }}
            image: {{ .Values.reaper.image }}
            args:
            - reaper
            env:
            - name: DEFAULT_TTL
              value: {{ .Values.reaper.defaultTTL }}
            - name: FIRST_EXPIRATION_WARNING
              value: {{ .Values.reaper.firstExpirationWarning }}
            - name: WARNING_INTERVAL
              value: {{ .Values.reaper.warningInterval }}
            - name: REAP_MESSAGE
              value: {{ .Values.reaper.messages.reapMessage }}
            - name: EXPIRATION_WARNING_MESSAGE
              value: {{ .Values.reaper.messages.expirationWarning }}
            - name: EXPIRATION_OVERDUE_MESSAGE
              value: {{ .Values.reaper.messages.expirationOverdue }}
            - name:
            - name: SLACK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "fullname.short" . }}-reaper-secret
                  key: slackApiKey
            - name: SLACK_CHANNEL_ID
              value: {{ .Values.reaper.slack.channelID }}
          restartPolicy: OnFailure
