apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname.short" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ include "fullname.short" . }}
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ include "fullname.short" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.sandboxer.image }}"
        imagePullPolicy: IfNotPresent
        resources:
{{ toYaml .Values.resources | indent 10 }}
