---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fullname.short" . }}
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fullname.short" . }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fullname.short" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "fullname.short" . }}
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fullname.short" . }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ["get", "list", "create", "update", "watch"]
- apiGroups:
  - devops.stackstate.com
  resources:
  - sandboxes
  - sandboxes/status
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - namespaces
  - serviceaccounts
  verbs: ["*"]
