# permissions for end users to edit sandboxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sandbox-editor-role
rules:
- apiGroups:
  - devops.stackstate.com
  resources:
  - sandboxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.stackstate.com
  resources:
  - sandboxes/status
  verbs:
  - get
